Repository never-alone-turing/never_alone_be, pull requests merged in 2020-12, with the labels that each got.

#13 User model
  app/models/user.rb
  db/migrate/20201219210933_create_users.rb
  db/schema.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: back_end, database, enhancement

#12 Group model setup
  app/models/group.rb
  db/migrate/20201219215428_create_groups.rb
  db/schema.rb
  spec/models/group_spec.rb
Labels: back_end, database, testing

#14 Create checkin table
  app/models/checkin.rb
  db/migrate/20201219222751_create_checkins.rb
  db/schema.rb
  spec/models/checkin_spec.rb
Labels: back_end, database, testing

#20 Add checkin relationships
  app/models/checkin.rb
  app/models/group.rb
  app/models/user.rb
  db/migrate/20201220023041_add_user_to_checkins.rb
  db/schema.rb
  spec/models/checkin_spec.rb
  spec/models/group_spec.rb
  spec/models/user_spec.rb
Labels: back_end, database

#19 Group user table
  app/models/group.rb
  app/models/group_user.rb
  app/models/user.rb
  db/migrate/20201220012419_create_group_users.rb
  db/schema.rb
  spec/models/group_user_spec.rb
Labels: back_end, database, testing
